TOP_DIR=../..
include ../config.mk
include ../part-pre.mk




HEADERS   += $(FUSG_LIB_HDRS)
INCLUDES  += $(FUSG_LIB_INCL)
OBJECTS   += $(FUSG_LIB)
LIBRARIES +=-lgdbm



EXECUTABLE=$(BUILD_DIR)/$(PART)



include ../part-post.mk

